config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  get 'top/index'
  get 'memos/main'
  post 'top/search'
  resources :memos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
  validates :content, presence: true
  validates :password, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def main
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(
    content: params[:memo][:content],
    password: params[:memo][:password],
    expiration_date: params[:memo][:expiration_date])
    if @memo.save
      redirect_to memo_path(@memo), alert: 'メモを作成しました'
    else
      render :main
    end
  end
  
  def show
    @memo = Memo.find_by(id: params[:id])
    if @memo.nil?
      redirect_to root_path, alert: 'メモが見つかりませんでした。'
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    redirect_to top_index_path
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def search
    @memo = Memo.find_by(password: params[:password])
    if @memo
      redirect_to memo_path(@memo)
    else
      redirect_to top_index_path, alert: '合言葉が正しくありません'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuickShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/main.html.erb
<div class='modal-body'>
  <%= form_with(model: @memo, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :content, 'メモ内容' %><br>
      <%= f.text_area :content, class: 'form-control' %>
    </div>
    <div class="form-group">
    <%= f.label :password, '合言葉' %>
    <%= f.text_field :password, class: 'form-control' %>
    <%= f.submit '共有', class: 'btn-btn-primary' %><br>
    <%= link_to 'TOPページ', top_index_path %><br>
    <%= link_to '新規メモ作成', memos_main_path %>
    </div>
  <% end %>
</div>

app/views/memos/show.html.erb
<div><%= @memo.content %></div><br>
<div>
<% qrcode = RQRCode::QRCode.new(request.url, level: :q) %>
<img src="<%= ChunkyPNG::Image.from_datastream(qrcode.as_png.resize(100, 100).to_datastream).to_data_url %>" alt="QR Code" />
<%= link_to 'TOPページ', top_index_path %>
<%= button_to '削除', memo_path(@memo), method: :delete, data: { confirm: '本当に削除しますか？' } %></div>

app/views/top/index.html.erb
<p>クイックシェア</p>


<p class='btn-primary'><%= link_to 'メモ作成', memos_main_path %></p>
<div1 class="modal-fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModalLabel" aria-hidden="true">
    <div2 class="modal-dialog" role="document">
        <div3 class="modal-content">
            <div4 class="modal-header">
                <p class="modal-title" id="a">メモ検索</p>
            </div4>
            <div5 class="modal-body">
                <%= form_with url: top_search_path, method: :post, local: true  do |f| %>
                <div class="form-group">
                    <%= f.label :password, '合言葉' %><br>
                    <%= f.text_field :password, class: 'form-control' %>
                </div6>

                </div><br>
                <%= f.submit '検索', class: 'btn-btn-primary' %>
                <% end %>
            </div>
        </div>
    </div>
</div>